### ISSUE TITLE
[BUG] NOT WOKRING NOW

### ISSUE THREAD

**Issue by wenfangdu** [FarhadG/init#17]
@FarhadG Recently, `init` stopped working, it might be caused by a recent GitHub update, please take a look!

**Comment by FarhadG** [comment]
Hi @wenfangdu. It continues to work for me. Make sure it's not a private repo since the API call won't return any information due to limited access.

**Comment by wenfangdu** [comment]
@FarhadG It does work now, but I'm certain that it didn't yesterday, since I tried `init` on multiple public repos including this one, GitHub might have fixed it.
