### ISSUE TITLE
Better way of finding the first commit 

### ISSUE THREAD

**Issue by JamesWP** [FarhadG/init#6]
Just thought I'd let you know about this way of getting the first commit:
I was trying to solve the same problem and noticed this 

https://gist.github.com/JamesWP/bc3622dd3d94bf6cbeb5c83b7f183b55

**Comment by FarhadG** [comment]
Thanks for sharing, @JamesWP. Perhaps it would be nice to have additional functionality with `init`  that would allow for someone to type in the repo name and go back instead of needing to be on the repo as well. I generally am on the repo and decide to see the first commit...

**Comment by FarhadG** [comment]
@JamesWP did you want to open a PR and incorporate this functionality? Would be great to have it merged with the other fork of your snippet which includes private repo support, as well. I think the combination of being able to query the dom and pick out the current repo you're would be a great addition to this snippet and bookmarklet.

**Comment by JamesWP** [comment]
I would want to if I had the time to look into this, however that might never happen so feel free to take the code provided if you get chance :)

**Comment by pitaj** [comment]
@JamesWP's version fails when the repo has only one "page" of commits. I updated his gist to work for all repos: https://gist.github.com/pitaj/e52862409dd5726711214a55189f332d

Here's the source for the bookmarklet I made which works great for me. Only works on browsers that support full ES6, though 😄 

    javascript:!function([,b,c]){return fetch(`https://api.github.com/repos/${b}/${c}/commits`).then(d=>Promise.all([d.headers.get('link'),d.json()])).then(([d,e])=>{if(d){const f=d.split(',')[1].split(';')[0].slice(2,-1);return fetch(f).then(g=>g.json())}return e}).then(d=>d[d.length-1].html_url).then(d=>window.location=d)}(window.location.pathname.split('/'));

**Comment by JamesWP** [comment]
Very nice, good spot for the big!

**Comment by JamesWP** [comment]
Bug *

**Comment by FarhadG** [comment]
Thanks for the update, @pitaj. Feel free to open a PR, since you've already made the bookmarklet work 👍 

There is a `gulp` task that minifies the JS, etc. if you need as well. We could add Babel support to compile the code, but I decided against it at first, so anyone wanting to use the bookmarklet can easily see the code and know what's happening (lean and intelligible).

**Comment by pitaj** [comment]
I doubt Babel is really necessary, right? I mean, I assume most people on Github who have need for a bookmarklet like this are using a capable browser.

**Comment by FarhadG** [comment]
Yes, that was my thought, as well, as I decided to write it with common JS features. If you were able to open a PR with your version updated to basic JS, I'd love to pull in the PR, @pitaj

**Comment by pitaj** [comment]
What counts as "common JS features" or "basic JS"?

**Comment by FarhadG** [comment]
I would say ES5 is common apart from the old browsers we're all aware of...

**Comment by pitaj** [comment]
Okay. ES5 is pretty damned verbose with Promises, though. How about ES5 + arrow functions?

**Comment by FarhadG** [comment]
I think that should be good. Very little change from your current setup and if users wanted, we could always offer two different version...

**Comment by FarhadG** [comment]
Btw, feel free to add a CONTRIBUTORS section to README with your PR to credit @pitaj  and @JamesWP's work.

**Comment by FarhadG** [comment]
PR merged into `master` and `gh-pages`. Thank you for the effort, @pitaj and @JamesWP.

**Comment by FarhadG** [comment]
One thing that I always found useful with the old way of getting the first commit was the ability to see the first page that contained the first commit. That way, I could walk through the commits easily, however, now that we go directly to the first commit, I haven't been able to find a way to go the next commit or see the page that contains those list of commits.

Thoughts? @JamesWP @pitaj

**Comment by pitaj** [comment]
I'm sure it's possible. But it's a choice between going to the init commit or going to the first page, not both.

**Comment by JamesWP** [comment]
Clicking on the bookmarklet -> if the page is already on the first commit go to the page containing the first commits otherwise go to the initial commit
